### ISSUE TITLE
Incorrect link fuckthesenetworks.sh

### ISSUE THREAD

**Issue by intari** [mxroute/da_server_updates#34]
hi,
https://mxroutedocs.com/presales/networkblocks/ says you do have https://github.com/mxroute/da_server_updates/blob/master/sec/fuckthesenetworks.sh
There is no such file. 
Is it error in documentation or repository?

**Comment by mxroute** [comment]
Good catch. The article should be removed. I'm currently rebuilding docs and expect to be done by end of week, so we'll just consider that one move.

**Comment by demyxco** [comment]
Hey @mxroute the link is still there.
